package com.example.accessingdatamysql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.util.UriComponentsBuilder;

import java.net.URI;

@Controller	// This means that this class is a Controller
@RequestMapping(path="/") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private PaisRepository paisRepository;


	@PostMapping(path="/pais")
	private ResponseEntity<Void> añadirPais(@RequestBody Pais nuevoPais, UriComponentsBuilder ucb) {
		Pais pais = new Pais(nuevoPais.getPais(), nuevoPais.getMoneda());
		paisRepository.save(pais);
		URI uriPais = ucb.path("/pais/").buildAndExpand(pais.getPais()).toUri();
		return ResponseEntity.created(uriPais).build();
	}

}
/*
TODO:
👉 Añadir pais: (Añadir unos automaticamente al iniciar la aplicacion)
	verbo a usar POST,
		datos:
			pais
			moneda

👉 get pais por nombre
👉 get de dos paises por nombre
👉	-crear metodo de comparacion de monedas
 */